# Generated by Django 3.0.5 on 2020-04-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
