# Generated by Django 3.0.5 on 2020-04-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='api.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(default='неплачено', max_length=50),
        ),
    ]
